### ISSUE TITLE
Tracking of V8 stopped working

### ISSUE THREAD

**Issue by bmeurer** [h4writer/arewefastyet#102]
Somehow V8 doesn't seem to be tracked anymore on AWFY. Anything we can/need to do?

**Comment by h4writer** [comment]
Thanks for notifying us and wiling to help. Something went wrong when updating to the new revisions. As last resort I just deleted the repository and re-cloned. Seems this worked?

**Comment by bmeurer** [comment]
Works again, thanks.

**Comment by bmeurer** [comment]
Looks like it stopped working again.

**Comment by h4writer** [comment]
I got the following issue:

bash-3.2$ make -j6 -C /Users/hannesverschore/awfy-new/repos/v8-32/v8 ia32.release
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/accessors.o
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/address-map.o
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/allocation.o
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/allocation-site-scopes.o
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/api-experimental.o
  CXX(target) /Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/api.o
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/accessors.o] Error 1
make[1]: *** Waiting for unfinished jobs....
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/api-experimental.o] Error 1
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/address-map.o] Error 1
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/allocation.o] Error 1
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/api.o] Error 1
error: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Werror,-Wunknown-warning-option]
make[1]: *** [/Users/hannesverschore/awfy-new/repos/v8-32/v8/out/ia32.release/obj.target/v8_base/src/allocation-site-scopes.o] Error 1
make: *** [ia32.release] Error 2

**Comment by bmeurer** [comment]
Looks like you need to run gclient sync first.

>

**Comment by h4writer** [comment]
It seems that the build system took the CC env variable which was wrong. Which it didn't before. Should be solved.

**Comment by bmeurer** [comment]
Thanks.

>

**Comment by bmeurer** [comment]
Looks like it stopped working again.

**Comment by h4writer** [comment]
This is the output I get:

```
>> Executing in /Users/hannesverschore/awfy-new/repos/v8-32/v8
git pull origin master
with: {'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LC_CTYPE': 'en_US.UTF-8', 'SSH_CLIENT': '192.168.0.149 37240 22', 'LOGNAME': 'hannesverschore', 'USER': 'hannesverschore', 'HOME': '/Users/hannesverschore', 'PATH': '/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8', 'TERM': 'screen', 'SHELL': '/bin/bash', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '2', 'PWD': '/Users/hannesverschore/awfy-new/slave', '_': '/usr/bin/python', 'LC_ALL': 'en_US.UTF-8', 'STY': '318.ttys000.Hanness-Mac-Pro', 'TMPDIR': '/var/folders/c3/w9g_ndg17m15ny3ggn5ts1hc0000gn/T/', 'TERMCAP': 'SC|screen|VT 100/ANSI X3.64 virtual terminal:\\\n\t:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\\n\t:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\\n\t:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\\n\t:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\\n\t:li#56:co#205:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\\n\t:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\\n\t:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\\n\t:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\\n\t:ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\\n\t:se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\\n\t:Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\\n\t:vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\\n\t:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\\n\t:po=\\E[5i:pf=\\E[4i:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:k3=\\EOR:\\\n\t:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:k8=\\E[19~:\\\n\t:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:F3=\\E[1;2P:\\\n\t:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:F7=\\E[15;2~:\\\n\t:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:kb=^H:K2=\\EOE:\\\n\t:kB=\\E[Z:kF=\\E[1;2B:kR=\\E[1;2A:*4=\\E[3;2~:*7=\\E[1;2F:\\\n\t:#2=\\E[1;2H:#3=\\E[2;2~:#4=\\E[1;2D:%c=\\E[6;2~:%e=\\E[5;2~:\\\n\t:%i=\\E[1;2C:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:@7=\\E[4~:\\\n\t:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:kd=\\EOB:\\\n\t:kr=\\EOC:kl=\\EOD:km:', 'LC_MESSAGES': 'en_US.UTF-8', 'SSH_TTY': '/dev/ttys000', 'LC_COLLATE': 'en_US.UTF-8', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'WINDOW': '0', 'MAIL': '/var/mail/hannesverschore', 'SSH_CONNECTION': '192.168.0.149 37240 192.168.0.128 22', 'OLDPWD': '/Users/hannesverschore/awfy-new/repos/v8-32'}
From https://chromium.googlesource.com/v8/v8
 * branch            master     -> FETCH_HEAD
Already up-to-date.

>> Executing in /Users/hannesverschore/awfy-new/repos/v8-32/v8
gclient sync
with: {'PATH': '/Users/hannesverschore/awfy-new/repos/v8-32/depot_tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'}

________ running '/usr/bin/python v8/gypfiles/landmines.py' in '/Users/hannesverschore/awfy-new/repos/v8-32'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s v8/buildtools/win/clang-format.exe.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
0> File v8/buildtools/mac/clang-format exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.004675 second(s)

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "linux*", skipping.

________ running '/usr/bin/python v8/tools/gcmole/download_gcmole_tools.py' in '/Users/hannesverschore/awfy-new/repos/v8-32'
Skipping gcmole download as gcmole is not set in gyp flags.

________ running '/usr/bin/python v8/tools/jsfunfuzz/download_jsfunfuzz.py' in '/Users/hannesverschore/awfy-new/repos/v8-32'
Skipping jsfunfuzz download as jsfunfuzz is not set in gyp flags.

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-luci -d v8/tools/luci-go/win64' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/Users/hannesverschore/awfy-new/repos/v8-32'
0> File v8/tools/luci-go/mac64/isolate exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.022135 second(s)

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "linux*", skipping.

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s v8/buildtools/win/gn.exe.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
0> File v8/buildtools/mac/gn exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.004972 second(s)

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/Users/hannesverschore/awfy-new/repos/v8-32'
The current platform doesn't match "linux*", skipping.

________ running '/usr/bin/python v8/gypfiles/vs_toolchain.py update' in '/Users/hannesverschore/awfy-new/repos/v8-32'

________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/Users/hannesverschore/awfy-new/repos/v8-32'

________ running '/usr/bin/python v8/gypfiles/download_gold_plugin.py' in '/Users/hannesverschore/awfy-new/repos/v8-32'
Gold plugin download not supported on windows.

________ running '/usr/bin/python v8/tools/clang/scripts/update.py --if-needed' in '/Users/hannesverschore/awfy-new/repos/v8-32'
Updating Clang to 267383-1...
Clang is already up to date.

________ running '/usr/bin/python v8/gypfiles/gyp_v8' in '/Users/hannesverschore/awfy-new/repos/v8-32'
Updating projects from gyp files...

>> Executing in /Users/hannesverschore/awfy-new/repos/v8-32/v8
make -j6 ia32.release
with: {'LC_ALL': 'en_US.UTF-8', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LC_CTYPE': 'en_US.UTF-8', 'SSH_CLIENT': '192.168.0.149 37240 22', 'LOGNAME': 'hannesverschore', 'USER': 'hannesverschore', 'PATH': '/Users/hannesverschore/awfy-new/repos/v8-32/depot_tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/Users/hannesverschore', 'STY': '318.ttys000.Hanness-Mac-Pro', '_': '/usr/bin/python', 'LANG': 'en_US.UTF-8', 'TERMCAP': 'SC|screen|VT 100/ANSI X3.64 virtual terminal:\\\n\t:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\\n\t:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\\n\t:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\\n\t:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\\n\t:li#56:co#205:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\\n\t:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\\n\t:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\\n\t:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\\n\t:ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\\n\t:se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\\n\t:Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\\n\t:vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\\n\t:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\\n\t:po=\\E[5i:pf=\\E[4i:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:k3=\\EOR:\\\n\t:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:k8=\\E[19~:\\\n\t:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:F3=\\E[1;2P:\\\n\t:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:F7=\\E[15;2~:\\\n\t:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:kb=^H:K2=\\EOE:\\\n\t:kB=\\E[Z:kF=\\E[1;2B:kR=\\E[1;2A:*4=\\E[3;2~:*7=\\E[1;2F:\\\n\t:#2=\\E[1;2H:#3=\\E[2;2~:#4=\\E[1;2D:%c=\\E[6;2~:%e=\\E[5;2~:\\\n\t:%i=\\E[1;2C:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:@7=\\E[4~:\\\n\t:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:kd=\\EOB:\\\n\t:kr=\\EOC:kl=\\EOD:km:', 'TERM': 'screen', 'SHELL': '/bin/bash', 'LC_MESSAGES': 'en_US.UTF-8', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '2', 'SSH_TTY': '/dev/ttys000', 'LC_COLLATE': 'en_US.UTF-8', 'WINDOW': '0', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/hannesverschore/awfy-new/slave', 'TMPDIR': '/var/folders/c3/w9g_ndg17m15ny3ggn5ts1hc0000gn/T/', 'MAIL': '/var/mail/hannesverschore', 'SSH_CONNECTION': '192.168.0.149 37240 192.168.0.128 22', 'OLDPWD': '/Users/hannesverschore/awfy-new/repos/v8-32'}
output was: PYTHONPATH="/Users/hannesverschore/awfy-new/repos/v8-32/v8/tools/generate_shim_headers:/Users/hannesverschore/awfy-new/repos/v8-32/v8/build::/Users/hannesverschore/awfy-new/repos/v8-32/v8/tools/gyp/pylib:" \
        GYP_GENERATORS=make \
        tools/gyp/gyp --generator-output="out" gypfiles/all.gyp \
                      -Igypfiles/standalone.gypi --depth=. \
                      -Dv8_target_arch=ia32 \
                       \
                       \
                      -S.ia32.release  -Dv8_enable_backtrace=1 -Darm_fpu=default -Darm_float_abi=default
gyp: Error importing pymod_do_mainmodule (detect_v8_host_arch): No module named detect_v8_host_arch
make: *** [out/Makefile.ia32.release] Error 1

Command '['make', '-j6', 'ia32.release']' returned non-zero exit status 2
Traceback (most recent call last):
  File "build.py", line 336, in <module>
    builder.build(puller)
  File "build.py", line 93, in build
    self.make()
  File "build.py", line 243, in make
    Run(args, self.env.get())
  File "/Users/hannesverschore/awfy-new/slave/utils.py", line 129, in Run
    raise e
subprocess.CalledProcessError: Command '['make', '-j6', 'ia32.release']' returned non-zero exit status 2
```

It complains about:
gyp: Error importing pymod_do_mainmodule (detect_v8_host_arch): No module named detect_v8_host_arch

Am I doing something wrong?

**Comment by h4writer** [comment]
Seems the build system of v8 is now fixed again!

**Comment by bmeurer** [comment]
Yes. It looks like some build system changes broke the build with make. Thanks for looking.
